tsuna/gohbase

- AUTHORS
This pull request is updating AUTHORS as well as meant to test our repos synchronization
> Update AUTHORS with myself

- client.go
- hrpc/call.go
- hrpc/scan.go
> Made scan work across regions, respect numberOfRows limit

- admin_client.go
- client.go
- region/client.go
- region/client_test.go
- region/new_go16.go
- region/new_go17.go
- region/test_new.go
- rpc.go
- rpc_test.go
@Timoha here is another one of the minor fixes I mentioend.
> Fix effective user for accessing region servers.

- hrpc/call.go
- hrpc/get.go
- hrpc/scan.go
- integration_test.go
- scanner.go
Re-based off main branch and added changes
> Add support for MaxResultsPerColumnFamily and ResultOffset

- admin_client.go
- hrpc/snapshot.go
- integration_test.go
- test/mock/adming_client.go
Add support for `ListSnapshot` to the admin client. Also fixes some comment nits I missed in the last commit.
> hrpc, gohbase: Add snapshot listing

- admin_client.go
- hrpc/list.go
- hrpc/snapshot.go
- integration_test.go
- test/mock/adming_client.go
> hrpc, gohbase: Add table listing to admin client

- client.go
- compression/codec.go
- compression/snappy/snappy.go
- compression/snappy/snappy_test.go
- go.mod
- go.sum
- hrpc/checkandput.go
- hrpc/hrpc_test.go
- hrpc/mutate.go
- mockrc_test.go
- region/client.go
- region/client_test.go
- region/compressor.go
- region/compressor_test.go
- region/multi.go
- region/multi_test.go
- region/new.go
- rpc.go
- rpc_test.go
- Implements cellblocks serialization for mutate and multi
- Adds snappy compression and decompression for cellblocks
> Add snappy compression between client and regionserver

- region/compressor.go
- region/compressor_test.go
The decompressor didn't handle hadoop's compression block streaming
format entirely. It only handled a single block prefixed by uncompressed
block length, however a response can contain multiple blocks like so:
<length of uncompressed block>
<length of compressed chunk><compressed chunk>
<length of compressed chunk><compressed chunk>
...
<length of compressed chunk><compressed chunk>
<length of uncompressed block>
<length of compressed chunk><compressed chunk>
...
...
The decompression was failing on longer responses that were split into
multiple blocks. The fix handles sequence of blocks.
> region: fix decompression of multiple blocks in response

- admin_client.go
- hrpc/balancer.go
- hrpc/move.go
- integration_test.go
- Add `SetBalancer` to enable/disable balancer
- Add `MoveRegion` to move regions
> New Admin APIs

- go.mod
- go.sum
> Update snappy to 0.0.4

- hrpc/call.go
- hrpc/get.go
- hrpc/query.go
- hrpc/scan.go
https://docs.cloudera.com/HDPDocuments/HDP2/HDP-2.2.9/bk_hadoop-ha/content/ha-hbase-timeline-consistency.html
> Allow specification of consistency with Get and Scan

- internal/observability/observability.go
Without this PR, exemplars are being captured for traces that are not being sampled
> tracing: Adjust exemplar logic to cater for non sampled traces

- region/new.go
- region/prometheus.go
> Revert "metrics: add bytes written & bytes read metric"

- rpc.go
Builds on #197 and simply adds a new span to `sendBlocking`.
> Sendblockingspan

- integration_test.go
- rpc.go
HBase row/rowkey[1] have a maximum length of `MAX_ROW_LENGTH` (MaxInt16 = 32767). 
When inserting a new row or scanning a table, gohbase needs to find the location of the regions. If the row inserted is of size MAX_ROW_LENGTH (or even slightly smaller) and the region location is unknown, gohbase will fail to locate the region. This happens because the generated meta key, used to scan the meta table, ends up being bigger than MAX_ROW_LENGTH. HBase will reject the request with the following exception:
```
java.io.IOException: startRow's length must be less than or equal to 32767 to meet the criteria for a row key
```
gohbase will exponentially retry forever, unless the context of the request is canceled.
The solution here is to make sure that the generated meta key is always smaller or …
> rpc: always generate metakey of len <= MAX_ROW_LENGTH

- rpc.go
> rpc: cap backoff retry at 30s

- rpc.go
- rpc_test.go
This change pulls out some of the refactoring that is being done for adding batch support into its own PR.
`*client.handleResultError` checks the error on an RPC response and takes action such as marking a client connection down or re-establishing a region.
`getRegionAndClientForRPC` finds the region and region client for an RPC and similarly handles the case of establishing/re-establishing a region.
`SendRPC` and `sendRPCToRegion` (now `sendRPCToRegionClient`), are shorter and simpler because the error handling has been pulled out. There should be no significant behavior changes. If I could easily, I would have deleted `sendRPCToRegionClient` and inlined its code in `SendRPC`, but it would have made testing it a bit harder.
> Refactor for batch

- rpc.go
- rpc_test.go
The clients cache can get out of sync with what regions are actually associated with a region server. A case has been seen where region points to a region client that doesn't exist in the clients map. When this occurs subsequent calls to clientDown are no-ops, and the bad region continues to point to the incorrect region server.
clientDown will now ensure that the given region is made unavailable, even if it is not found in the clients list of regions.
closes: #186
> Ensure region is made unavailable in clientDown

- region/client.go
The old implementation had lots of different conditions that were hard to think through, some uninuitive behaviors, and at least one bug.
First the bug: when flushInterval == 0, the flush reason is always "queue full". It should be "timeout" if we flush before filling the batch. This is fixed in the new loop.
Old implementation if flushInterval == 0:
1) do a nonblocking read of rpcs chan in a loop
2) check if you read anything in that loop
2a) if not, do a blocking read to get at least one RPC
and then go back to 1.
2b) if yes, flush and start over
Old implementation if flushInterval > 0:
1) do a nonblocking read of rpcs chan in a loop
2) check if you read anything in that loop
2a) if not, do a blocking read to get at least one RPC
and then go back to 1.
2b) if yes, and size of batch is …
> region: Reimplement processRPCs batching loop

- region/client.go
Reverts tsuna/gohbase#231: performance testing showed regression
> Revert "region: Reimplement processRPCs batching loop"

- region/info.go
- region/info_test.go
Properly convert []byte to string and add Client field in addition to client pointer
> Fix logging to properly convert byte array to string
