client.go, rpc.go, zk/client.go
@Timoha this is the replacement PR for #21. It contains the fix you mentioned in there as well.
=> Added support for alternative zookeeper path roots.

admin_client.go, caches.go, client.go, integration_test.go, region/client.go, rpc.go, scanner.go, zk/client.go
Logrus authors recommend that references to the logrus package use only the lowercase variation. See https://github.com/sirupsen/logrus/blob/master/README.md
End user code will not build unless that code and all of its dependencies follow only a single logrus case convention.
=> using recommended lowercase reference to logrus

client.go, rpc.go
@timoha this fixes a couple lint issues. Unfortunately there are still two instances that golint complains about, even after these changes, but I cannot fix them without breaking backwards compatibility. This is, however, super annoying as most IDEs will show squiggles under these files because of it.
The remaining lint issues are:
```
client.go:156:6: func RpcQueueSize should be RPCQueueSize
rpc.go:37:2: error var TableNotFound should have name of the form ErrFoo
```
I understand that changing these would break backwards compatibility, but since vendoring is the norm in Go, I am wondering if we can make an exception just this once and make these changes?
At the very least, I would request that linting is run automatically going forward. Perhaps we can integrate it into the CI system?
=> Fixed a couple linting issues.

hrpc/scan.go, integration_test.go, scanner.go, scanner_test.go
HBase offers reverse scanning functionality which can be very useful with time series keys. 
Initial attempt did not change regions correctly, but after reviewing the java code for this, I think this is handling region changes in a similar way.
Included integration tests with the test table pre-split for my test data ranges.
=> Implement reverse scanner

hrpc/call.go, hrpc/hrpc_test.go
Forward the stringer so that hrpc.Cell can be displayed in
diagnostic/error messages.
=> hrpc: forward hrpc.Cell stringer to protobuf

admin_client.go, hrpc/snapshot.go, integration_test.go, test/mock/adming_client.go
One design decision here was to use leave it up to clients to disable & re-enable the table which is required for restoring a snapshot. An alternative option is to handle that in the function call. Let me know if you think it's better to go with the alternative.
=> hrpc, gohbase: Add snapshot restoration

hrpc/scan.go, integration_test.go, scanner.go, scanner_test.go
This PR fixes two bugs on closing region scanners:
1. During scanning multiple regions, GoHBase requests a new region scanner on server side  when current region is exhausted, without closing the current one on server side. The fix uses the scanner id to close (https://issues.apache.org/jira/browse/HBASE-18000)
2. At the end of scan, gohbase always calls to close the scanner on server side. Some scan requests, such as meta lookups, has closeScanner flag set so server auto close them after the first response. This redundant call also causes the server( without the fix in https://issues.apache.org/jira/browse/HBASE-17489 ) to throw errors. hbase meta lookup request is called for every table access so this behavior almost doubles the load on hbase meta. For older version of hhase, it also …
=> Fix problems with closing region scanners.

region/client_test.go
The test was expecting that the scheduler would let
processRPCs goroutine to read several RPCs before moving on
to next goroutine. In case the sheduler lets processRPC to only
process one RPC at a time, we would end up with a call to regionserver
for each RPC (no batching). This can be especially reproduced with
-race flag.
Instead we should expect that at most there would be as many batches
as RPCs.
=> region: fix TestProcessRPCs/2 test

hrpc/call.go, hrpc/get.go, hrpc/hrpc_test.go, hrpc/mutate.go, hrpc/query.go, hrpc/query_test.go, hrpc/scan.go
Client.proto already has this defined as cache_blocks in the models for Get and Scan. This allows users of the hrpc to set the attribute per request.
Also adding some tests for Get and Scan ToProto methods.
=> hrpc: expose CacheBlocks options for get/scan queries

hrpc/scan.go, scanner.go
We are calling Close() on scanner internally when there's no more data,
the client might also additionally call Close() themselves causing
unexpected for them error.
=> Don't return error on subsequent closing of scanner

hrpc/mutate.go
This PR adds a function to expose the Mutate object's values field.
It is envisioned that this would aid in estimating the amount of work
that is about to be done (for use in metrics and tracing annotations).
=> Expose Mutate.values

region/compressor.go, region/compressor_test.go
Pre-allocating the output buffer drastically reduce the number of allocations made (and thus, the number of garbage object created):
```
name                                     old time/op    new time/op    delta
DecompressCellblocks1/BlockLen10-12        42.2ns ± 0%    43.2ns ± 1%   +2.40%  (p=0.016 n=4+5)
DecompressCellblocks1/BlockLen100-12        244ns ± 4%     168ns ± 0%  -31.29%  (p=0.008 n=5+5)
DecompressCellblocks1/BlockLen1000-12      1.68µs ± 1%    1.33µs ± 3%  -21.07%  (p=0.008 n=5+5)
DecompressCellblocks1/BlockLen10000-12     19.2µs ± 5%    12.9µs ± 3%  -32.77%  (p=0.008 n=5+5)
DecompressCellblocks10/BlockLen10-12        288ns ± 2%     300ns ± 1%   +4.28%  (p=0.008 n=5+5)
DecompressCellblocks10/BlockLen100-12      1.78µs ± 1%    1.98µs ± 1%  +11.34%  (p=0.008 n=5+5) …
```
=> region: optimisee decompressCellblocks

region/multi.go
In the case where trace sampling is applied, it could be that events are added with traceIDs that will not be readable.
This change simply indicates this state.
=> tracing: indicate whether traces are sampled

region/new.go, region/prometheus.go
This change adds two new counter vector metrics:
- bytes_read_total - number of bytes read by a regionserver connection 
- bytes_written_total - number of bytes written to a regionserver connection
These metrics have one label - regionserver - which indicates the address of the connection used.
=> metrics: add bytes written & bytes read metric

region/client.go, region/multi.go, region/multi_test.go
It is confusing to have a different span for processRPCs and not likely to be
used by viewers of the data. To track the time an RPC spends in the
processRPCs loop we can add a span to that RPC's context as it enters
the loop and close the span when the RPC is flushed. Though, that has not been implemented here.
Once the span is removed from processRPCs, much of the code related to
open telemetry tracing is no longer needed in the region package.
=> Remove context on multis

hrpc/checkandput.go, hrpc/hrpc_test.go, hrpc/mutate.go, region/client.go, region/multi.go, region/multi_test.go
A handful of changes to optimize serialization of a multi into cellblocks with a big emphasis on reducing allocations.
The current state of the code does about one allocation per value in a call plus around 6 allocations per call. The MultiToProtoLarge benchmark creates a multi with 1000 calls, each with 5 values and would result in 11.2k allocations. 
The code in this change brings it to roughly 4 allocations per call in a multi and removes the per-value allocation, bringing the allocation count to 4.2k in MultiToProtoLarge.
The MultiToProto (not large) benchmark creates a multi with 5 calls, each with 0 or 1 value. It does not see as much benefits from these changes. The common case is sending a large multi, so I think that tradeoff is worth it.
```
name                             old …
```
=> Optimize multi serialization

region/client.go, region/prometheus.go
This will expose the size of batches being sent by gohbase.
Buckets are [1, 5, 25, 125, 625, 3125, 15625, 78125]. This should capture all expected sizes of batches and importantly count all the batches that have exactly 1 request in them. In one setup I saw 90% of batches containing exactly 1 request and in another the 99.9%tile value was ~3100 with spikes over 8000.
=> region: Add batch_flush_size histogram metric

hrpc/call.go, mockrc_test.go, region/client.go, region/client_test.go, region/info_test.go, region/multi.go, region/multi_test.go, region/new.go, rpc.go, rpc_test.go, test/mock/region/client.go
Added the API:
```
SendBatch(ctx context.Context, batch []hrpc.Call) (res []hrpc.RPCResult, allOK bool)
```
The res has results in the same order as the RPCs in batch. Each RPCResult contains a result and an error. If the error is non-nil then the RPC failed or was not attempted. If it's nil the batch succeeded. The allOK is false if any of the results contain an error.
closes #68, closes #117
=> Add SendBatch API

region/client.go, region/client_test.go
Wrap connection in a bufio.Reader for reading RPC responses from RegionServer. This should reduce the number of read system calls by attempting to fill a 4KB buffer on each read.
Some mock tests that expected certain sizes of buffers passed to Read() had to be made more lenient.
=> region: Use a buffered reader

prometheus.go, rpc.go
Instead of starting goroutines we can queue each region server's collection of RPCs and only after queueing them all wait for all responses. We get a similar amount of parallelism, the only potential slow down is that we can't queue one region server's RPCs until the previous is able to be queued.
By not starting goroutines, the resource usage of SendBatch is more predictable. And not starting goroutines is likely to be less expensive overall.
This change also adds a new metric for number of splits that occur in SendBatch.
=> SendBatch: Don't start goroutines

hrpc/create.go, table_test.go
=> hrpc: allow table creation with table attributes

rpc.go, rpc_test.go
To match the behavior of SendRPC, SendBatch should retry RPCs that hit retryable errors: region.RetryableError, region.ServerError, and region.NotServingRegionError.
SendBatch will now retry each RPC that hits a retryable error. What used to be a single step through of assigning regions to RPCs, grouping them by region server and then dispatching the RPCs to their respective servers, is now done in a loop. The first iteration of the loop operates on the entire batch. Later iterations operate on the set of RPCs that failed with retryable errors in the previous batch.
=> SendBatch: Retry retryable errors

hrpc/snapshot.go
HBase has 2 snapshot formats: version 0 and version 2. Version 2 is more efficient as it doesn't require the creation of thousand of empty files and instead create a single manifest file[1].
The snapshot format version is dependent of the SnapshotDescription. When the version is not set, HBase will use the default version. In HBase 1.x/2.x, the default version is 2.
Unfortunately, gohbase implementation always set the version to 0, even when the caller didn't explicitly set the version. This is is because internally gohbase use an int32 (not a pointer) which default to 0 implicitly.
This change switch the internal storage to a pointer, to match the "optional" behaviour on the protobuf side.
[1] More details at:
- https://issues.apache.org/jira/browse/HBASE-7987
- …
=> hrpc/snapshot: keep version unset if not specified

admin_client.go, client.go, debug_state_test.go, mockrc_test.go, region/client.go, region/new.go, rpc.go, rpc_test.go, zk/client.go
Fixes #248
This change allows for overriding the default dialers used by the ZooKeeper client and the Region client to connect to their respective servers. Proxy-aware dialers can be installed by people who need them.
=> Expose Dialers inside Zk and Region

client.go, integration_test.go, region/client.go, region/info.go, region/new.go, rpc.go, rpc_test.go, test/mock/client.go
This change adds an option in gohbase to prepopulate its region cache. It does a single scan of the meta table and cache all regions.
=> cache: added region cache warmup

region/client.go, region/compressor.go, region/compressor_test.go
Replace `growBuffer` with `append` and `resizeBufferCap` with `slices.Grow`. And remove redundant `if` checks on capacity or size that `append` will do as well. This is equivalent behavior after undoing the unintentional change from commit https://github.com/tsuna/gohbase/commit/1fee39f343954ca7501a6b8f25abd9f86eaf618b. Benchmarks show the performance is equivalent to the code before commit https://github.com/tsuna/gohbase/commit/1fee39f343954ca7501a6b8f25abd9f86eaf618b.
Also replace some deprecated calls to rand funcs.
=> region: Simplify buffer funcs

admin_client.go, caches.go, client.go, debug_state_test.go, go.mod, go.sum, integration_test.go, mockrc_test.go, region/client.go, region/client_test.go, region/new.go, rpc.go, rpc_test.go, zk/client.go
Fixes: #247 
We are using log/slog instead of logrus, and replace logrus fatal log level (which doesn't exist in slog) with panic
=> Replace logrus with log/slog for logging

scanner.go, scanner_test.go
HBase server already close the region scanner[1] when there is no more results to be send from that region. Therefore, it is useless to send one more request to close the scanner.
[1] https://github.com/apache/hbase/blob/rel/2.5.8/hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java#L3698-L3701
=> scanner: don't send scanner close request when region was exhausted

internal/observability/observability.go, rpc.go
Improve the observability of RPC spans by including the table and key. The values are quoted to improve readability of table and key values that combine printable unicode characters with non-printable raw binary. For example, "\xc4x03Qux".
=> gohbase: Add table and key attributes to span

hrpc/call.go, hrpc/query.go, hrpc/query_test.go, region/client.go
Provide an option for setting the priority on a Scan or Get request. The priority is set on the RequestHeader, so must be set by the region code when serializing the request.
=> hrpc, region: Allow setting priority on Scan and Get requests

hrpc/query.go, hrpc/query_test.go, region/client.go, scanner.go
If a scanner needs to scan multiple times ensure all scanners get the priority set in the initial hrpc.Scan.
Updated baseQuery.Priority to return a uint32 rather than a *uint32 to be less weird.
=> Keep priority on scanner's subsequent scans

hrpc/call.go, hrpc/query.go, region/client.go, rpc.go
Add a couple helpers to remove type asserts.
=> hrpc: Add CanBatch and GetPriority helpers

rpc.go
When warming up the cache, ignore regions that are offline/unassigned. They could exist for many reasons:
- parent region after a split, until daughter regions are compacted
- regions that are merged together, until compaction happens
- region moving due to HBase LoadBalancer, RegionServer shutting down or manually
- etc
It's not critical if we are missing a few regions in the cache during warmup. The most important thing is for the warmup to be fast and to fill in with as many regions as possible. Other regions will be fetched later as needed.
=> rpc: ignore offline/unassigned regions during cache warmup

admin_client.go, hrpc/query_test.go, hrpc/snapshot.go, integration_test.go
Add method to change the table of the hrpc.Snapshot. By setting the snapshot to a new table name that doesn't already exist, the data in the snapshot can be cloned into this new table instead of being restored to the table the snapshot was created from.
=> AdminClient: set snapshot table and apply snapshot to new table

.github/workflows/ci.yml, hrpc/hrpc_test.go, hrpc/scan.go, integration_test.go, scanner.go
This change adds an option to Scan (Renew) that allows for renewal of scanners during periods of starvation to prevent lease timeout. Currently, we are renewing every lease timeout / 2 seconds (10s currently).
=> add renewal for scanner to prevent lease timeout

client.go, integration_test.go, prometheus.go, scanner.go, scanner_test.go
Most calls to Next are just reading some buffered results. The scanner renewer only needs to be stopped and started again when we ask for more results from HBase. Also, we shouldn't start a renewer if we know we have already fetched the final results.
=> Don't restart scanner renewer on every Next call

hrpc/call.go, hrpc/hrpc_test.go, hrpc/move.go, region/compressor_test.go
There are several places with redundant type casting. Presumably, many if not all of these were probably due to constraints of the early Go compiler. Although there is a certain readability aspect, there is potential over- head in redundant casts. The Go compiler might add in overhead to cast (e.g., `string` to `[]byte`). These were found with GoLand's linter.
=> root: Remove Redundant Type Casting

region/client.go, rpc.go
When receiving ServerNotRunningYetException, a client shouldn't retry to send the request to the same server. Instead, the client should be closed and the region lookup should happen again.
There is two cases when ServerNotRunningYetException is returned:
- when the RegionServer is listening but not online yet: in that case, retrying the RPC on the same server may succeed if the Regionserver become ready and if the region is indeed assigned to it. But most likely the region would have been reassigned to another Regionserver and thus it will return NotServingRegionException in the following request. If the Regionserver is stuck in startup phase, it could also cause the client to be stuck in retry loop whereas HBasemaster may have detected the issue and correctly moved the region to another …
=> region/client: re-establish connection on ServerNotRunningYetException

integration_test.go, region/new.go, table_test.go
Old-style build tags no longer needed. They can be removed. Sorry, they were bugging me.
=> Root: Remove Old Build Tags

rpc.go, rpc_test.go
When a scan attempt returns an error that originates from sendBlocking, there won't be a ScanResponse (the RPCResult will be nil). In this case when updating the ScanStats and while ScanMetrics are enabled, an unclear error level log message was logged. This change clarifies the log message and moves the log level to debug, as well as skipping the check when there's a nil RPCResult.
=> rpc: clarify logging for ScanStats with ScanMetrics

hrpc/scan.go, rpc.go, rpc_test.go
Add ResponseSize to ScanStats. To get this value to the ScanStats the cellblocks size is stored on the *hrpc.Scan during DeserializeCellBlocks.
=> Add ResponseSize to ScanStats
